steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/$_APP_NAME:$SHORT_SHA
      - -t
      - gcr.io/$PROJECT_ID/$_APP_NAME:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$_APP_NAME'

  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - $_APP_NAME

      - '--image'
      - 'gcr.io/$PROJECT_ID/$_APP_NAME:latest'
      - '--port'
      - '8000'

      - '--region'
      - $_REGION

      - '--platform'
      - managed

      - '--allow-unauthenticated'

      - '--min-instances=0'
      - '--max-instances=1'
      - '--concurrency=80'
      - '--timeout=5s'
      - '--cpu=$_CPU'
      - '--memory=$_MEMORY'
      - '--service-account=$_SERVICE_ACCOUNT'

options:
  logging: CLOUD_LOGGING_ONLY
